= Smittestopp Backend

image:https://github.com/folkehelseinstituttet/Fhi.Smittestopp.Backend/workflows/.NET%20Core/badge.svg[]
image:https://img.shields.io/github/issues/folkehelseinstituttet/Fhi.Smittestopp.Backend[]
image:https://img.shields.io/github/issues-pr/folkehelseinstituttet/Fhi.Smittestopp.Backend[]
image:https://img.shields.io/github/last-commit/folkehelseinstituttet/Fhi.Smittestopp.Backend[]

//TODO: describe what is the project about

== Installation

// event log registration

// mention `Application Path` not having `api`.

=== Requirements
// it needs windows

== Usage

// links to EN API

// gateway is not integrated for now

// hangfire jobs
// hangfire service

// mention sql job

=== Swagger
// mention swagger attributes

=== Configuration
// jwt endpoint

==== API version deprecation
`AppSettings` section of `appsettings.json` configuration enables setting a specific version of API as deprecated.

To set version `1` and version `2` as deprecated put `"1"` and `"2"` strings into `DeprecatedVersions` array.
Use example below for reference.

.appsettings.json
[source,json]
----
{
  "AppSettings": {
    "DeprecatedVersions": [
      "1",
      "2"
    ]
  }
}
----

Calling an endpoint in deprecated version will result in getting a response with the code `410` and content `API is deprecated`.

==== Logging configuration
The project uses different logging solutions when it comes to backend logs and mobile logs.

===== Backend logs
Backend uses solution provided by the framework, described in
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0[Logging in .NET Core and ASP.NET Core].
`Startup` class calls `AddFile` extension method to also save logs to a file.

===== Mobile logs
Application running on devices pushes its logs using `/logging/logMessages` endpoint.
`LoggingController` receives those logs and saves them using `log4net` package.
This package uses `log4net.config` configuration file.


// mobile token


== Contributing

// mention Translation table is not used for now

// mention gateway code is not used for now

// ContainerRegistration pattern for unit tests

// Generic repository pattern

// appsetting managemetn
// (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1)

=== Database connection
// mention
//
//## Migrations
//### Command for creating a new migration
//`DIGNDB.App.SmitteStop\DIGNDB.App.SmitteStop.API>dotnet ef migrations add <MigrationName> --project ../DIGNDB.App.SmitteStop.DAL`

== License
Copyright (c) 2020 Agency for Digitisation (Denmark), 2020 Norwegian Institute of Public Health (Norway), 2020 Netcompany Group AS

Smittestopp is Open Source software released under the link:LICENSE.md[MIT license]
