= Smittestopp Backend

image:https://github.com/folkehelseinstituttet/Fhi.Smittestopp.Backend/workflows/.NET%20Core/badge.svg[]
image:https://img.shields.io/github/issues/folkehelseinstituttet/Fhi.Smittestopp.Backend[]
image:https://img.shields.io/github/issues-pr/folkehelseinstituttet/Fhi.Smittestopp.Backend[]
image:https://img.shields.io/github/last-commit/folkehelseinstituttet/Fhi.Smittestopp.Backend[]

//TODO: describe what is the project about

== Installation

// event log registration

// mention `Application Path` not having `api`.

=== Requirements
// it needs windows

== Usage

// links to EN API

// hangfire jobs
// hangfire service

// mention sql job

=== Swagger
// mention swagger attributes

=== Configuration

The project uses the standard ASP`.NET Core` mechanism for splitting configuration for different environments.
To get yourself familiar with the concept take a look at this article https://docs.microsoft.com/en-us/aspnet/core/fundamentals/environments?view=aspnetcore-3.1[Use multiple environments in ASP.NET Core]

==== Mobile token

Some endpoints require a _mobile token_ because of `MobileAuthorizationAttribute` attribute.
This token provides static authentication mechanism between the backend and the mobile app.

You need to provide this token to `appsettings.json` configuration for all environments apart from `development`.

.appsettings.json
[source,json]
----
{
  "AppSettings": {
    "AuthorizationMobile": "To be replaced in Pipelines"
  }
}
----

To generate this token just pick a random string (treat it like a password, the longer and higher entropy the better), share it with the mobile team, encrypt it using `ConfigEncryptionHelper.ProtectString` and put it into `AuthorizationMobile` value.
This method `ProtectString` uses `Data Protection API` under the hood, so you need to **repeat this encryption for each server**.

==== JWT validation
Endpoint `POST /diagnostickeys` uses JWT token to authenticate the client.

You can configure some JWT validation rules using the configuration below.

.appsettings.json
[source,json]
----
{
  "JwtAuthorization" : {
    "JwtValidationRules": {
      "ClientId": "To be replaced in Pipelines",  <1>
      "SupportedAlgorithm": "RS256",              <2>
      "Issuer": "To be replaced in Pipelines"     <3>
    },
    "JwkUrl": "To be replaced in Pipelines"       <4>
  }
}
----
<1> Client id from the token, which we consider valid.
<2> Supported signature algorithm, which we consider valid.
<3> Issuer from the token, which we consider valid.
<4> Url from which the validator service will retrieve _the public key_.

==== API version deprecation
`AppSettings` section of `appsettings.json` configuration enables setting a specific version of API as deprecated.

To set version `1` and version `2` as deprecated put `"1"` and `"2"` strings into `DeprecatedVersions` array.
Use example below for reference.

.appsettings.json
[source,json]
----
{
  "AppSettings": {
    "DeprecatedVersions": [
      "1",
      "2"
    ]
  }
}
----

Calling an endpoint in deprecated version will result in getting a response with the code `410` and content `API is deprecated`.

==== Logging configuration
The project uses different logging solutions when it comes to backend logs and mobile logs.

===== Backend logs
Backend uses solution provided by the framework, described in
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0[Logging in .NET Core and ASP.NET Core].
`Startup` class calls `AddFile` extension method to also save logs to a file.

===== Mobile logs
Application running on devices pushes its logs using `/logging/logMessages` endpoint.
`LoggingController` receives those logs and saves them using `log4net` package.
This package uses `log4net.config` configuration file.

== Contributing

=== Unused code

Don't feel surprised to find some portions of unused code.
As an example, you won't find any logical usages of `Translation` table or whole `FederationGatewayApi` project.
Development team removed the code using it because the project should not integrate with
https://github.com/eu-federation-gateway-service/efgs-federation-gateway[EU Federation Gateway Service] for now.

=== Patterns used in the project

==== Generic repository

To access the database please use `GenericRepository<T>` class.
Feel free to create a custom repository class based on the generic one if needed.

==== Dependency registration

Each module should have its dependencies registered in a separate extension method.

For example in `DIGNDB.App.SmitteStop.DAL` module we have a method presented below.

[source,c#]
----
public static class ContainerRegistration
{
    public static IServiceCollection AddDALDependencies(this IServiceCollection services)
    {
        services.AddScoped<IJwtTokenRepository, JwtTokenRepository>();
        services.AddScoped<ICountryRepository, CountryRepository>();
        services.AddScoped(typeof(IGenericRepository<>), typeof(GenericRepository<>));

        return services;
    }
}
----

This pattern provides a number of benefits.

. It keeps all the registration calls in one place per module.
. It enables marking some implementation classes as internal (encapsulation).
. It the need for mocking in unit tests (see link:./DIGNDB.App.SmitteStop.Testing/ServiceTest/JwtValidationServiceTests.cs[JWT validation tests] as an example).

=== Database connection
To develop the project you need a working `SQL Server` instance.
You can either use a local instance or a `Docker` container.

==== Entity Framework Code First
The project utilizes `Code First` with Migrations approach when using `Entity Framework` package.

Please pay attention when running `dotnet ef` commands.
The database context lays in different project (`DIGNDB.App.SmitteStop.DAL`)
than the `API` so you need to specify the context project each time.

For example to create a new migration run the following command:

[source]
----
DIGNDB.App.SmitteStop\DIGNDB.App.SmitteStop.API>dotnet ef migrations add <MigrationName> --project ../DIGNDB.App.SmitteStop.DAL
----

== License
Copyright (c) 2020 Agency for Digitisation (Denmark), 2020 Norwegian Institute of Public Health (Norway), 2020 Netcompany Group AS

Smittestopp is Open Source software released under the link:LICENSE.md[MIT license]
