// <auto-generated />
using System;
using DIGNDB.App.SmitteStop.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DIGNDB.App.SmitteStop.DAL.Migrations
{
    [DbContext(typeof(DigNDB_SmittestopContext))]
    [Migration("20210128113028_FixedTranslationsSeederAndRemovedUnusedTranslationColumn")]
    partial class FixedTranslationsSeederAndRemovedUnusedTranslationColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DIGNDB.App.SmitteStop.Domain.Db.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PullingFromGatewayEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("VisitedCountriesEnabled")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "AT",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 2L,
                            Code = "BE",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 3L,
                            Code = "BG",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 4L,
                            Code = "HR",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 5L,
                            Code = "CY",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 6L,
                            Code = "CZ",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 8L,
                            Code = "EE",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 9L,
                            Code = "FI",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 10L,
                            Code = "FR",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 11L,
                            Code = "DE",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 12L,
                            Code = "GR",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 13L,
                            Code = "HU",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 14L,
                            Code = "IE",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 15L,
                            Code = "IT",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 16L,
                            Code = "LV",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 17L,
                            Code = "LT",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 18L,
                            Code = "LU",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 19L,
                            Code = "MT",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 20L,
                            Code = "NL",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 21L,
                            Code = "PL",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 22L,
                            Code = "PT",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 23L,
                            Code = "RO",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 24L,
                            Code = "SK",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 25L,
                            Code = "SI",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 26L,
                            Code = "ES",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 27L,
                            Code = "SE",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 7L,
                            Code = "DK",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 29L,
                            Code = "NO",
                            PullingFromGatewayEnabled = false,
                            VisitedCountriesEnabled = false
                        },
                        new
                        {
                            Id = 28L,
                            Code = "EN",
                            PullingFromGatewayEnabled = false,
                            VisitedCountriesEnabled = false
                        },
                        new
                        {
                            Id = 30L,
                            Code = "IS",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 31L,
                            Code = "LI",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 32L,
                            Code = "CH",
                            PullingFromGatewayEnabled = true,
                            VisitedCountriesEnabled = true
                        },
                        new
                        {
                            Id = 33L,
                            Code = "NB",
                            PullingFromGatewayEnabled = false,
                            VisitedCountriesEnabled = false
                        },
                        new
                        {
                            Id = 34L,
                            Code = "NN",
                            PullingFromGatewayEnabled = false,
                            VisitedCountriesEnabled = false
                        });
                });

            modelBuilder.Entity("DIGNDB.App.SmitteStop.Domain.Db.JwtToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("JwtToken");
                });

            modelBuilder.Entity("DIGNDB.App.SmitteStop.Domain.Db.Setting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("DIGNDB.App.SmitteStop.Domain.Db.TemporaryExposureKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newid())");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("DaysSinceOnsetOfSymptoms")
                        .HasColumnType("int");

                    b.Property<byte[]>("KeyData")
                        .IsRequired()
                        .HasColumnType("varbinary(255)")
                        .HasMaxLength(255);

                    b.Property<int>("KeySource")
                        .HasColumnType("int");

                    b.Property<long>("OriginId")
                        .HasColumnType("bigint");

                    b.Property<int>("ReportType")
                        .HasColumnType("int");

                    b.Property<long>("RollingPeriod")
                        .HasColumnType("bigint");

                    b.Property<long>("RollingStartNumber")
                        .HasColumnType("bigint");

                    b.Property<bool>("SharingConsentGiven")
                        .HasColumnType("bit");

                    b.Property<int>("TransmissionRiskLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KeyData")
                        .IsUnique();

                    b.HasIndex("OriginId");

                    b.ToTable("TemporaryExposureKey");
                });

            modelBuilder.Entity("DIGNDB.App.SmitteStop.Domain.Db.TemporaryExposureKeyCountry", b =>
                {
                    b.Property<Guid>("TemporaryExposureKeyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint");

                    b.HasKey("TemporaryExposureKeyId", "CountryId");

                    b.HasIndex("CountryId");

                    b.ToTable("TemporaryExposureKeyCountry");
                });

            modelBuilder.Entity("DIGNDB.App.SmitteStop.Domain.Db.Translation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("EntityId")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LanguageCountryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageCountryId");

                    b.ToTable("Translation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            EntityId = 1L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Austria"
                        },
                        new
                        {
                            Id = 2L,
                            EntityId = 2L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Belgium"
                        },
                        new
                        {
                            Id = 3L,
                            EntityId = 3L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Bulgaria"
                        },
                        new
                        {
                            Id = 4L,
                            EntityId = 4L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Croatia"
                        },
                        new
                        {
                            Id = 5L,
                            EntityId = 5L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Cyprus"
                        },
                        new
                        {
                            Id = 6L,
                            EntityId = 6L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Czech Republic"
                        },
                        new
                        {
                            Id = 7L,
                            EntityId = 7L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Denmark"
                        },
                        new
                        {
                            Id = 8L,
                            EntityId = 8L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Estonia"
                        },
                        new
                        {
                            Id = 9L,
                            EntityId = 9L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Finland"
                        },
                        new
                        {
                            Id = 10L,
                            EntityId = 10L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "France"
                        },
                        new
                        {
                            Id = 11L,
                            EntityId = 11L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Germany"
                        },
                        new
                        {
                            Id = 12L,
                            EntityId = 12L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Greece"
                        },
                        new
                        {
                            Id = 13L,
                            EntityId = 13L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Hungary"
                        },
                        new
                        {
                            Id = 14L,
                            EntityId = 14L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Ireland"
                        },
                        new
                        {
                            Id = 15L,
                            EntityId = 15L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Italy"
                        },
                        new
                        {
                            Id = 16L,
                            EntityId = 16L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Latvia"
                        },
                        new
                        {
                            Id = 17L,
                            EntityId = 17L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Lithuania"
                        },
                        new
                        {
                            Id = 18L,
                            EntityId = 18L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Luxembourg"
                        },
                        new
                        {
                            Id = 19L,
                            EntityId = 19L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Malta"
                        },
                        new
                        {
                            Id = 20L,
                            EntityId = 20L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Netherlands"
                        },
                        new
                        {
                            Id = 21L,
                            EntityId = 21L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Poland"
                        },
                        new
                        {
                            Id = 22L,
                            EntityId = 22L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Portugal"
                        },
                        new
                        {
                            Id = 23L,
                            EntityId = 23L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Romania"
                        },
                        new
                        {
                            Id = 24L,
                            EntityId = 24L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Slovakia"
                        },
                        new
                        {
                            Id = 25L,
                            EntityId = 25L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Slovenia"
                        },
                        new
                        {
                            Id = 26L,
                            EntityId = 26L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Spain"
                        },
                        new
                        {
                            Id = 27L,
                            EntityId = 27L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Sweden"
                        },
                        new
                        {
                            Id = 28L,
                            EntityId = 28L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Iceland"
                        },
                        new
                        {
                            Id = 29L,
                            EntityId = 29L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Liechtenstein"
                        },
                        new
                        {
                            Id = 30L,
                            EntityId = 30L,
                            EntityName = "Country",
                            LanguageCountryId = 28L,
                            Value = "Switzerland"
                        },
                        new
                        {
                            Id = 31L,
                            EntityId = 1L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Østerrike"
                        },
                        new
                        {
                            Id = 32L,
                            EntityId = 2L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Belgia"
                        },
                        new
                        {
                            Id = 33L,
                            EntityId = 3L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Bulgaria"
                        },
                        new
                        {
                            Id = 34L,
                            EntityId = 4L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Kroatia"
                        },
                        new
                        {
                            Id = 35L,
                            EntityId = 5L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Kypros"
                        },
                        new
                        {
                            Id = 36L,
                            EntityId = 6L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Tsjekkia"
                        },
                        new
                        {
                            Id = 37L,
                            EntityId = 7L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Danmark"
                        },
                        new
                        {
                            Id = 38L,
                            EntityId = 8L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Estland"
                        },
                        new
                        {
                            Id = 39L,
                            EntityId = 9L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Finland"
                        },
                        new
                        {
                            Id = 40L,
                            EntityId = 10L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Frankrike"
                        },
                        new
                        {
                            Id = 41L,
                            EntityId = 11L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Tyskland"
                        },
                        new
                        {
                            Id = 42L,
                            EntityId = 12L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Hellas"
                        },
                        new
                        {
                            Id = 43L,
                            EntityId = 13L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Ungarn"
                        },
                        new
                        {
                            Id = 44L,
                            EntityId = 14L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Irland"
                        },
                        new
                        {
                            Id = 45L,
                            EntityId = 15L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Italia"
                        },
                        new
                        {
                            Id = 46L,
                            EntityId = 16L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Latvia"
                        },
                        new
                        {
                            Id = 47L,
                            EntityId = 17L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Litauen"
                        },
                        new
                        {
                            Id = 48L,
                            EntityId = 18L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Luxembourg"
                        },
                        new
                        {
                            Id = 49L,
                            EntityId = 19L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Malta"
                        },
                        new
                        {
                            Id = 50L,
                            EntityId = 20L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Nederland"
                        },
                        new
                        {
                            Id = 51L,
                            EntityId = 21L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Polen"
                        },
                        new
                        {
                            Id = 52L,
                            EntityId = 22L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Portugal"
                        },
                        new
                        {
                            Id = 53L,
                            EntityId = 23L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Romania"
                        },
                        new
                        {
                            Id = 54L,
                            EntityId = 24L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Slovakia"
                        },
                        new
                        {
                            Id = 55L,
                            EntityId = 25L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Slovenia"
                        },
                        new
                        {
                            Id = 56L,
                            EntityId = 26L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Spania"
                        },
                        new
                        {
                            Id = 57L,
                            EntityId = 27L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Sverige"
                        },
                        new
                        {
                            Id = 58L,
                            EntityId = 28L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Island"
                        },
                        new
                        {
                            Id = 59L,
                            EntityId = 29L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Liechtenstein"
                        },
                        new
                        {
                            Id = 60L,
                            EntityId = 30L,
                            EntityName = "Country",
                            LanguageCountryId = 33L,
                            Value = "Sveits"
                        },
                        new
                        {
                            Id = 61L,
                            EntityId = 1L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Austerrike"
                        },
                        new
                        {
                            Id = 62L,
                            EntityId = 2L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Belgia"
                        },
                        new
                        {
                            Id = 63L,
                            EntityId = 3L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Bulgaria"
                        },
                        new
                        {
                            Id = 64L,
                            EntityId = 4L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Kroatia"
                        },
                        new
                        {
                            Id = 65L,
                            EntityId = 5L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Kypros"
                        },
                        new
                        {
                            Id = 66L,
                            EntityId = 6L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Tsjekkia"
                        },
                        new
                        {
                            Id = 67L,
                            EntityId = 7L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Danmark"
                        },
                        new
                        {
                            Id = 68L,
                            EntityId = 8L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Estland"
                        },
                        new
                        {
                            Id = 69L,
                            EntityId = 9L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Finland"
                        },
                        new
                        {
                            Id = 70L,
                            EntityId = 10L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Frankrike"
                        },
                        new
                        {
                            Id = 71L,
                            EntityId = 11L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Tyskland"
                        },
                        new
                        {
                            Id = 72L,
                            EntityId = 12L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Hellas"
                        },
                        new
                        {
                            Id = 73L,
                            EntityId = 13L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Ungarn"
                        },
                        new
                        {
                            Id = 74L,
                            EntityId = 14L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Irland"
                        },
                        new
                        {
                            Id = 75L,
                            EntityId = 15L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Italia"
                        },
                        new
                        {
                            Id = 76L,
                            EntityId = 16L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Latvia"
                        },
                        new
                        {
                            Id = 77L,
                            EntityId = 17L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Litauen"
                        },
                        new
                        {
                            Id = 78L,
                            EntityId = 18L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Luxembourg"
                        },
                        new
                        {
                            Id = 79L,
                            EntityId = 19L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Malta"
                        },
                        new
                        {
                            Id = 80L,
                            EntityId = 20L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Nederland"
                        },
                        new
                        {
                            Id = 81L,
                            EntityId = 21L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Polen"
                        },
                        new
                        {
                            Id = 82L,
                            EntityId = 22L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Portugal"
                        },
                        new
                        {
                            Id = 83L,
                            EntityId = 23L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Romania"
                        },
                        new
                        {
                            Id = 84L,
                            EntityId = 24L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Slovakia"
                        },
                        new
                        {
                            Id = 85L,
                            EntityId = 25L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Slovenia"
                        },
                        new
                        {
                            Id = 86L,
                            EntityId = 26L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Spania"
                        },
                        new
                        {
                            Id = 87L,
                            EntityId = 27L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Sverige"
                        },
                        new
                        {
                            Id = 88L,
                            EntityId = 28L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Island"
                        },
                        new
                        {
                            Id = 89L,
                            EntityId = 29L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Liechtenstein"
                        },
                        new
                        {
                            Id = 90L,
                            EntityId = 30L,
                            EntityName = "Country",
                            LanguageCountryId = 34L,
                            Value = "Sveits"
                        });
                });

            modelBuilder.Entity("DIGNDB.App.SmitteStop.Domain.Db.TemporaryExposureKey", b =>
                {
                    b.HasOne("DIGNDB.App.SmitteStop.Domain.Db.Country", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("DIGNDB.App.SmitteStop.Domain.Db.TemporaryExposureKeyCountry", b =>
                {
                    b.HasOne("DIGNDB.App.SmitteStop.Domain.Db.Country", "Country")
                        .WithMany("TemporaryExposureKeyCountries")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DIGNDB.App.SmitteStop.Domain.Db.TemporaryExposureKey", "TemporaryExposureKey")
                        .WithMany("VisitedCountries")
                        .HasForeignKey("TemporaryExposureKeyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DIGNDB.App.SmitteStop.Domain.Db.Translation", b =>
                {
                    b.HasOne("DIGNDB.App.SmitteStop.Domain.Db.Country", "LanguageCountry")
                        .WithMany("EntityTranslations")
                        .HasForeignKey("LanguageCountryId");
                });
#pragma warning restore 612, 618
        }
    }
}
