using Google.Protobuf;
using static FederationGatewayApi.Models.Proto.TemporaryExposureKeyGatewayDto.Types;

namespace FederationGatewayApi.Models.Proto
{
    /// <summary>
    /// Partial class to add new features to the autogenerated code
    /// </summary>
    public partial class TemporaryExposureKeyGatewayDto
    {
        private const int SecTo10Min = 60 * 10;

        public TemporaryExposureKeyGatewayDto(byte[] keyData, uint rollingStart, uint rollingDuration, int transmissionRisk, int daysSinceOnsetOfSymptoms, ReportType reportType)
        {
            this.KeyData = ByteString.CopyFrom(keyData);
            this.RollingStartIntervalNumber = rollingStart;
            this.RollingPeriod = rollingDuration;
            this.TransmissionRiskLevel = transmissionRisk;
            this.DaysSinceOnsetOfSymptoms = daysSinceOnsetOfSymptoms;
            this.ReportType = reportType;
        }

        /// <summary>
        /// Returns RollingStartIntervalNumber as a UnixTime not as 10 minutes intervals
        /// </summary>
        public long RollingStartIntervalNumberNormalized => RollingStartIntervalNumber * SecTo10Min;
    }
}
