name: Download and upload covid files 
on:
  schedule:
    - cron: '0/20 11-16 * * *' # UTC 
  workflow_dispatch:

jobs:
  download_dagens_tal:
    runs-on: ubuntu-latest
    steps:
    
    # Set env.date
    - name: Set date env
      id: step_date
      run: |
        echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    
    # Set env.base=base_url
    - name: Set base url
      id: step_base_url
      run: |
        echo "base_url=https://raw.githubusercontent.com/folkehelseinstituttet/surveillance_data/master/covid19" >> $GITHUB_ENV
    
    # Set env.file_tested
    - name: Set tested file name
      id: step_tested_file_name
      run: |
        echo "file_tested=data_covid19_lab_by_time_${{ env.date }}.csv" >> $GITHUB_ENV
    
    # Set env.file_hosp_admission
    - name: Set hospital admission file name
      id: step_hospital_admission
      run: |
        echo "file_hosp_admission=data_covid19_hospital_by_time_${{ env.date }}.csv" >> $GITHUB_ENV
    
    # Set env.file_vaccination
    - name: Set vaccination file name
      id: step_vaccination_file_name
      run: |
        echo "file_vaccination=data_covid19_sysvak_by_time_location_${{ env.date }}.csv" >> $GITHUB_ENV
    
    # Set env.file_time_location
    - name: Set time location file name
      id: step_time_location_file_name
      run: |
        echo "file_time_location=data_covid19_msis_by_time_location_${{ env.date }}.csv" >> $GITHUB_ENV
    
    # Set env.file_location
    - name: Set location file name
      id: step_location_file_name
      run: |
        echo "file_location=data_covid19_msis_by_location_${{ env.date }}.csv" >> $GITHUB_ENV
        
    #############################
    # Download and upload files #
    #############################
    
    # tested file
    - name: Check tested file uploaded
      id: check_tested_file_uploaded
      run: |
        response_tested_check=$(curl -s -o /dev/null -I -w "%{http_code}" "${{env.base_url}}/uploadStatistics?filename=${{env.file_tested}}")
        echo "Download check tested file response: $response_tested_check"
        if [ "true" == "${response_tested_check}" ]
        then
          echo "File already uploaded"
        else
          echo "File not uploaded yet"
        fi
        echo "tested_check_response=${response_tested_check}" >> $GITHUB_ENV
    - name: Download tested file
      id: download_tested_file
      run: |
        response_tested=$(curl -s -o /dev/null -I -w "%{http_code}" "${{env.base_url}}/${{env.file_tested}}")
        echo "Download tested file response: $response_tested"
        if [ "200" == "${response_tested}" ]
        then
          curl "${{env.base_url}}/${{env.file_tested}}" -o ${{env.file_tested}}          
          echo "Download of ${{env.file_tested}} completed"
        else
          echo "Download failure: ${response_tested}"
        fi
        echo "tested_response=${response_tested}" >> $GITHUB_ENV
    - name: Upload tested file
      id: upload_tested_file
      run: |
        echo "Download of ${{env.file_tested}} response: ${{env.tested_response}}"
        if [ "200" == "${{env.tested_response}}" ]
        then
          echo "Uploading file: ${{env.file_tested}}"
          response_tested_upload=$(curl -H "Authorization_GitHub: ${{ secrets.UPLOAD_STATS_H_VAL }}" -F "file=@${{env.file_tested}}" ${{secrets.UPLOAD_URL}})
          echo "Upload response: ${response_tested_upload}"
        else
          echo "File for ${{env.file_tested}} not available yet"
        fi       
    
    # hospital admission file
    - name: Download hospital admission file
      id: download_hospital_admission_file
      run: |
        response_hosp=$(curl -s -o /dev/null -I -w "%{http_code}" "${{env.base_url}}/${{env.file_hosp_admission}}")
        echo "Download hospital admission file response: $response_hosp"
        if [ "200" == "${response_hosp}" ]
        then
          curl "${{env.base_url}}/${{env.file_hosp_admission}}" -o ${{env.file_hosp_admission}}          
          echo "Download of ${{env.file_hosp_admission}} completed"
        else
          echo "Download failure: ${response_hosp}"
        fi
        echo "hosp_response=${response_hosp}" >> $GITHUB_ENV
    - name: Upload hospital admission file
      id: upload_hospital_admission_file
      run: |
        echo "Download of ${{env.file_hosp_admission}} response: ${{env.hosp_response}}"
        if [ "200" == "${{env.hosp_response}}" ]
        then
          echo "Uploading file: ${{env.file_hosp_admission}}"
          response_hosp_upload=$(curl -H "Authorization_GitHub: ${{ secrets.UPLOAD_STATS_H_VAL }}" -F "file=@${{env.file_hosp_admission}}" ${{secrets.UPLOAD_URL}})
          echo "Upload response: ${response_hosp_upload}"
        else
          echo "File for ${{env.file_hosp_admission}} not available yet"
        fi
        
    # time location file
    - name: Download time location file
      id: download_time_location_file
      run: |
        response_time_location=$(curl -s -o /dev/null -I -w "%{http_code}" "${{env.base_url}}/${{env.file_time_location}}")
        echo "Download time location file response: $response_time_location"
        if [ "200" == "${response_time_location}" ]
        then
          curl "${{env.base_url}}/${{env.file_time_location}}" -o ${{env.file_time_location}}          
          echo "Download of ${{env.file_time_location}} completed"
        else
          echo "Download failure: ${response_time_location}"
        fi
        echo "time_location_response=${response_time_location}" >> $GITHUB_ENV
    - name: Upload time location file
      id: upload_time_location_file
      run: |
        echo "Download of ${{env.file_time_location}} response: ${{env.time_location_response}}"
        if [ "200" == "${{env.time_location_response}}" ]
        then
          echo "Uploading file: ${{env.file_time_location}}"
          response_time_location_upload=$(curl -H "Authorization_GitHub: ${{ secrets.UPLOAD_STATS_H_VAL }}" -F "file=@${{env.file_time_location}}" ${{secrets.UPLOAD_URL}})
          echo "Upload response: ${response_time_location_upload}"
        else
          echo "File for ${{env.file_time_location}} not available yet"
        fi
    
    # location file
    - name: Download location file
      id: download_location_file
      run: |
        response_location=$(curl -s -o /dev/null -I -w "%{http_code}" "${{env.base_url}}/${{env.file_location}}")
        echo "Download location file response: $response_location"
        if [ "200" == "${response_location}" ]
        then
          curl "${{env.base_url}}/${{env.file_location}}" -o ${{env.file_location}}          
          echo "Download of ${{env.file_location}} completed"
        else
          echo "Download failure: ${response_location}"
        fi
        echo "location_response=${response_location}" >> $GITHUB_ENV
    - name: Upload location file
      id: upload_location_file
      run: |
        echo "Download of ${{env.file_location}} response: ${{env.location_response}}"
        if [ "200" == "${{env.location_response}}" ]
        then
          echo "Uploading file: ${{env.file_location}}"
          response_location_upload=$(curl -H "Authorization_GitHub: ${{ secrets.UPLOAD_STATS_H_VAL }}" -F "file=@${{env.file_location}}" ${{secrets.UPLOAD_URL}})
          echo "Upload response: ${response_location_upload}"
        else
          echo "File for ${{env.file_location}} not available yet"
        fi
        
  # vaccination file
    - name: Download vaccination file
      id: download_vaccination_file
      run: |
        response_vaccination=$(curl -s -o /dev/null -I -w "%{http_code}" "${{env.base_url}}/${{env.file_vaccination}}")
        echo "Download vaccination file response: $response_vaccination"
        if [ "200" == "${response_vaccination}" ]
        then
          curl "${{env.base_url}}/${{env.file_vaccination}}" -o ${{env.file_vaccination}}          
          echo "Download of ${{env.file_vaccination}} completed"
        else
          echo "Download failure: ${response_vaccination}"
        fi
        echo "vaccination_response=${response_vaccination}" >> $GITHUB_ENV
    - name: Upload vaccination file
      id: upload_vaccination_file
      run: |
        echo "Download of ${{env.file_vaccination}} response: ${{env.vaccination_response}}"
        if [ "200" == "${{env.vaccination_response}}" ]
        then
          echo "Uploading file: ${{env.file_vaccination}}"
          response_vaccination_upload=$(curl -H "Authorization_GitHub: ${{ secrets.UPLOAD_STATS_H_VAL }}" -F "file=@${{env.file_vaccination}}" ${{secrets.UPLOAD_URL}})
          echo "Upload response: ${response_vaccination_upload}"
        else
          echo "File for ${{env.file_vaccination}} not available yet"
        fi

